### ISSUE TITLE
Wrong schema path by ProcessSchemaIncludes

### ISSUE THREAD

**Issue by ryanbnl** [lenardg/WSDLMerge#1]
Lenard, there's a small bug in WSDLMerger.cs line 186.

There you recursively load includes, but send the filename of the parent schema, not the schema you just loaded.

ProcessSchemaIncludes(manager, filename, wsdl, newSchema);

Should be:

ProcessSchemaIncludes(manager, importLocation, wsdl, newSchema);

Let me know if I you'd like me to issue a pull request :)

**Comment by lenardg** [comment]
If you already fixed it, please do send a pull request :)

**Comment by nageshever** [comment]
Hi, is this issue resolved and committed to github? I have a XSDs with multiple levels of import statements, and looks like failing at second level and more. Seems to be above reported issue.
